"""Write build metadata for packaged releases.

Generates stickynotes/_build_info.py with __version__ and __build_date__
read from stickynotes/__init__.py. Dev runs omit this file and use mtime fallback.
"""

from __future__ import annotations

import re
import sys
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
INIT_PY = ROOT / "stickynotes" / "__init__.py"
BUILD_INFO_PY = ROOT / "stickynotes" / "_build_info.py"


def _read_version(init_text: str) -> str:
    match = re.search(r'__version__\s*=\s*["\']([^"\']+)["\']', init_text)
    if not match:
        raise SystemExit(f"Could not find __version__ in {INIT_PY}")
    return match.group(1)


def stamp() -> None:
    init_text = INIT_PY.read_text(encoding="utf-8")
    version = _read_version(init_text)
    build_date = datetime.now().strftime("%Y-%m-%d %H:%M")
    BUILD_INFO_PY.write_text(
        (
            '"""Build metadata — auto-generated by scripts/stamp_build_info.py."""\n'
            "\n"
            f'__version__ = "{version}"\n'
            f'__build_date__ = "{build_date}"\n'
        ),
        encoding="utf-8",
    )
    print(f"Stamped v{version} built {build_date} -> {BUILD_INFO_PY.relative_to(ROOT)}")


def clean() -> None:
    if BUILD_INFO_PY.exists():
        BUILD_INFO_PY.unlink()
        print(f"Removed {BUILD_INFO_PY.relative_to(ROOT)}")


def main(argv: list[str] | None = None) -> None:
    args = argv if argv is not None else sys.argv[1:]
    if args == ["--clean"]:
        clean()
    elif not args:
        stamp()
    else:
        raise SystemExit(f"Usage: {Path(__file__).name} [--clean]")


if __name__ == "__main__":
    main()
